version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - nolintlint
    - errorlint
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/8gears/godebug

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    for-loops: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
    - path: testdata/
      linters:
        - errcheck
        - govet
